tasks:
  - name : FlaskWebServer
    init: cd Flask && pip install -r requirements.txt && flask run # runs during prebuild
  - name : AngWebServer
    init: cd sitoweb && npm i -g @angular/cli && npm install replace-in-file --save-dev && npm update && node ./replace.build.js && ng serve --disable-host-check # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-browser
    visibility : public 
  - port: 5000
    visibility : public